// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eVote360Pro.Infrastructure.Persistence.Contexts;

#nullable disable

namespace eVote360Pro.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(eVote360ProContext))]
    partial class eVote360ProContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PoliticalPartyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PoliticalPartyId");

                    b.ToTable("Candidates", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Citizen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.ToTable("Citizens", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Election", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TotalCandidates")
                        .HasColumnType("int");

                    b.Property<int?>("TotalParties")
                        .HasColumnType("int");

                    b.Property<int?>("TotalPositions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Elections", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.ElectionParticipation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CitizenId")
                        .HasColumnType("int");

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FinalizedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.HasIndex("ElectionId", "CitizenId")
                        .IsUnique();

                    b.ToTable("ElectionParticipations", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.ElectivePosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ElectivePositions", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.PartyPositionAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssigningPartyId")
                        .HasColumnType("int");

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("ElectivePositionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssigningPartyId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ElectivePositionId");

                    b.ToTable("PartyPositionAssignments", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.PoliticalAlliance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcceptedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequesterPartyId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TargetPartyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequesterPartyId");

                    b.HasIndex("TargetPartyId");

                    b.ToTable("PoliticalAlliances", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.PoliticalParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Acronym")
                        .IsUnique();

                    b.ToTable("PoliticalParties", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PoliticalPartyId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PoliticalPartyId")
                        .IsUnique()
                        .HasFilter("[PoliticalPartyId] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.VerificationCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CitizenId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GenerationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.HasIndex("ElectionId");

                    b.ToTable("VerificationCodes", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("CitizenId")
                        .HasColumnType("int");

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<int>("ElectivePositionId")
                        .HasColumnType("int");

                    b.Property<int?>("PoliticalPartyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("CitizenId");

                    b.HasIndex("ElectionId");

                    b.HasIndex("ElectivePositionId");

                    b.HasIndex("PoliticalPartyId");

                    b.ToTable("Votes", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Candidate", b =>
                {
                    b.HasOne("eVote360Pro.Core.Domain.Entities.PoliticalParty", "PoliticalParty")
                        .WithMany("Candidates")
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PoliticalParty");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.ElectionParticipation", b =>
                {
                    b.HasOne("eVote360Pro.Core.Domain.Entities.Citizen", "Citizen")
                        .WithMany("Participations")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.Election", "Election")
                        .WithMany("Participations")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citizen");

                    b.Navigation("Election");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.PartyPositionAssignment", b =>
                {
                    b.HasOne("eVote360Pro.Core.Domain.Entities.PoliticalParty", "AssigningParty")
                        .WithMany("AssignedPositions")
                        .HasForeignKey("AssigningPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.Candidate", "Candidate")
                        .WithMany("PositionAssignments")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.ElectivePosition", "ElectivePosition")
                        .WithMany("CandidateAssignments")
                        .HasForeignKey("ElectivePositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssigningParty");

                    b.Navigation("Candidate");

                    b.Navigation("ElectivePosition");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.PoliticalAlliance", b =>
                {
                    b.HasOne("eVote360Pro.Core.Domain.Entities.PoliticalParty", "RequesterParty")
                        .WithMany("AlliancesAsRequester")
                        .HasForeignKey("RequesterPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.PoliticalParty", "TargetParty")
                        .WithMany("AlliancesAsReceiver")
                        .HasForeignKey("TargetPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequesterParty");

                    b.Navigation("TargetParty");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.User", b =>
                {
                    b.HasOne("eVote360Pro.Core.Domain.Entities.PoliticalParty", "PoliticalParty")
                        .WithOne("User")
                        .HasForeignKey("eVote360Pro.Core.Domain.Entities.User", "PoliticalPartyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PoliticalParty");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.VerificationCode", b =>
                {
                    b.HasOne("eVote360Pro.Core.Domain.Entities.Citizen", "Citizen")
                        .WithMany("VerificationCodes")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.Election", "Election")
                        .WithMany("VerificationCodes")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citizen");

                    b.Navigation("Election");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Vote", b =>
                {
                    b.HasOne("eVote360Pro.Core.Domain.Entities.Candidate", "Candidate")
                        .WithMany("Votes")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eVote360Pro.Core.Domain.Entities.Citizen", "Citizen")
                        .WithMany("Votes")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.Election", "Election")
                        .WithMany("Votes")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.ElectivePosition", "ElectivePosition")
                        .WithMany("Votes")
                        .HasForeignKey("ElectivePositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.PoliticalParty", "PoliticalParty")
                        .WithMany("Votes")
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Candidate");

                    b.Navigation("Citizen");

                    b.Navigation("Election");

                    b.Navigation("ElectivePosition");

                    b.Navigation("PoliticalParty");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Candidate", b =>
                {
                    b.Navigation("PositionAssignments");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Citizen", b =>
                {
                    b.Navigation("Participations");

                    b.Navigation("VerificationCodes");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Election", b =>
                {
                    b.Navigation("Participations");

                    b.Navigation("VerificationCodes");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.ElectivePosition", b =>
                {
                    b.Navigation("CandidateAssignments");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.PoliticalParty", b =>
                {
                    b.Navigation("AlliancesAsReceiver");

                    b.Navigation("AlliancesAsRequester");

                    b.Navigation("AssignedPositions");

                    b.Navigation("Candidates");

                    b.Navigation("User");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
